Error: NativeViewGestureHandler must be used as a descendant of GestureHandlerRootView
https://stackoverflow.com/questions/76957042/error-nativeviewgesturehandler-must-be-used-as-a-descendant-of-gesturehandlerro

TouchableOpacity from react-native-gesture-handler instead of react-native